
# Name of the robot that wants to enter a lift
string robot_name

# Name of the lift that the robot wants to enter
string lift_name

---

uint32 decision
uint32 DECISION_CLEAR = 1
uint32 DECISION_CROWDED = 2
