# Submit Task | "POST" service call

# Whom that call this srv 
string requester

# generated task ID by dispatcher node
string task_id

---

# Confirmation that this service call is processed
bool success
