# Cancel Task | "Delete" service call

# Identifier for who is requesting the service
string requester

# generated task ID by dispatcher node
string task_id

---

# Confirmation that this service call is processed
bool success
