# Query list of submitted tasks | Get service call
# Note: Still in design!!!!

# Whom that request this task
string requester

# generated task ID by dispatcher node
# if empty, provide all 
string[] task_id

---

bool success

TaskSummary[] active_tasks
TaskSummary[] terminated_tasks
