# Submit Task | POST service call

# Whom that call this srv
string requester

# Desired start time of a task
builtin_interfaces/Time start_time

# Task type
uint32 task_type
uint32 TASK_TYPE_STATION=0
uint32 TASK_TYPE_LOOP=1
uint32 TASK_TYPE_DELIVERY=2
uint32 TASK_TYPE_CHARGING=3
uint32 TASK_TYPE_CLEANING=4
uint32 TASK_TYPE_PATROL=5

# Task definitions
Station station
Loop loop
Delivery delivery
# Charge charge
Clean clean
# Patrol patrol

---

# Confirmation that this service call is processed
bool success

# generated task ID by dispatcher node
string task_id
