# The identifier for the task 
string task_id

# The identifier for the fleet that is bidding
string fleet_id

# The time needed to complete the task
uint64 seconds_needed

---

# True if the task was assigned to this fleet; false if assigned to others
bool task_assigned
