
# The query to be registered
ScheduleQuerySpacetime query

---

# The ID given to the registered query. Use this ID when making a query request.
uint64 query_id

# A string to notify exceptional issues that came up while trying to fulfill the
# request.
string error
