
# The ID of the query description to use
uint64 query_id

# The last known version of the mirror
uint64 last_version

---

# The patch for the query
SchedulePatch patch

# A description of any errors that were encountered, such as the query_id being
# unknown
string error
