
uint64 participant_id

---

# Confirmation that the participant was unregistered
bool confirmation


# A description of any errors that were encountered, such as the participant_id
# being unknown
string error
