name: style
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo apt-get update
    - name: rmf_uncrustify
      shell: bash
      run: |
        source /opt/ros/eloquent/setup.bash
        ament_uncrustify -c rmf_utils/test/format/rmf_code_style.cfg rmf_traffic/ rmf_traffic_ros2/ rmf_fleet_adapter/include/ rmf_fleet_adapter/test/ rmf_fleet_adapter/src/
